'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IGetLog")>  _
Public Interface IGetLog
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGetLog/GetServerLog", ReplyAction:="http://tempuri.org/IGetLog/GetServerLogResponse")>  _
    Function GetServerLog() As String()
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGetLog/GetServerLog", ReplyAction:="http://tempuri.org/IGetLog/GetServerLogResponse")>  _
    Function GetServerLogAsync() As System.Threading.Tasks.Task(Of String())
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface IGetLogChannel
    Inherits IGetLog, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class GetLogClient
    Inherits System.ServiceModel.ClientBase(Of IGetLog)
    Implements IGetLog
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Function GetServerLog() As String() Implements IGetLog.GetServerLog
        Return MyBase.Channel.GetServerLog
    End Function
    
    Public Function GetServerLogAsync() As System.Threading.Tasks.Task(Of String()) Implements IGetLog.GetServerLogAsync
        Return MyBase.Channel.GetServerLogAsync
    End Function
End Class
